// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2023- Mapiah Ltda

/// Therion UIS point symbols implemented as faithful vector drawings, one
/// value per `p_*_UIS` MetaPost macro ported to Dart.
enum MPTherionPointSymbol {
  airDraughtSummerUIS,
  airDraughtUIS,
  airDraughtWinterUIS,
  anastomosisUIS,
  archeoMaterialUIS,
  blocksUIS,
  campUIS,
  continuationUIS,
  crystalUIS,
  curtainUIS,
  curtainsUIS,
  debrisUIS,
  discPillarUIS,
  discPillarsUIS,
  discStalactiteUIS,
  discStalactitesUIS,
  discStalagmiteUIS,
  discStalagmitesUIS,
  diskUIS,
  digUIS,
  entranceUIS,
  flowstoneUIS,
  fluteUIS,
  gradientUIS,
  guanoUIS,
  helictiteUIS,
  helictitesUIS,
  iceUIS,
  karrenUIS,
  lowEndUIS,
  moonmilkUIS,
  narrowEndUIS,
  paleoMaterialUIS,
  pebblesUIS,
  pillarUIS,
  pillarsUIS,
  pillarWithCurtainsUIS,
  pillarsWithCurtainsUIS,
  popcornUIS,
  sandUIS,
  scallopUIS,
  sodaStrawUIS,
  stalactiteUIS,
  stalactitesUIS,
  stalactiteStalagmiteUIS,
  stalactitesStalagmitesUIS,
  stalagmiteUIS,
  stalagmitesUIS,
  wallCalciteUIS,
  waterFlowIntermittentUIS,
  waterFlowPaleoUIS,
  waterFlowPermanentUIS,
  waterUIS,
}
