// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2023- Mapiah Ltda

/// Therion point symbols implemented as faithful vector drawings, one value
/// per `p_*_<SET>` MetaPost macro ported to Dart (UIS first, then each
/// additional set as it's ported).
enum MPTherionPointSymbol {
  airDraughtSummerUIS,
  airDraughtUIS,
  airDraughtWinterUIS,
  anastomosisUIS,
  archeoMaterialUIS,
  blocksUIS,
  campUIS,
  continuationUIS,
  crystalUIS,
  curtainUIS,
  curtainsUIS,
  debrisUIS,
  discPillarUIS,
  discPillarsUIS,
  discStalactiteUIS,
  discStalactitesUIS,
  discStalagmiteUIS,
  discStalagmitesUIS,
  diskUIS,
  digUIS,
  entranceUIS,
  flowstoneUIS,
  fluteUIS,
  gradientUIS,
  guanoUIS,
  helictiteUIS,
  helictitesUIS,
  iceUIS,
  karrenUIS,
  lowEndUIS,
  moonmilkUIS,
  narrowEndUIS,
  paleoMaterialUIS,
  pebblesUIS,
  pillarUIS,
  pillarsUIS,
  pillarWithCurtainsUIS,
  pillarsWithCurtainsUIS,
  popcornUIS,
  sandUIS,
  scallopUIS,
  sodaStrawUIS,
  stalactiteUIS,
  stalactitesUIS,
  stalactiteStalagmiteUIS,
  stalactitesStalagmitesUIS,
  stalagmiteUIS,
  stalagmitesUIS,
  wallCalciteUIS,
  waterFlowIntermittentUIS,
  waterFlowPaleoUIS,
  waterFlowPermanentUIS,
  waterUIS,

  // SKBB (Phase 4B)
  anchorSKBB,
  boreholeSKBB,
  bridgeSKBB,
  campSKBB,
  cavePearlSKBB,
  claySKBB,
  fixedLadderSKBB,
  gradientSKBB,
  noEquipmentSKBB,
  ropeLadderSKBB,
  ropeSKBB,
  sinkSKBB,
  snowSKBB,
  springSKBB,
  stepsSKBB,
  traverseSKBB,
  viaFerrataSKBB,
}
