enum MPCommandDescriptionType {
  addElements,
  addLine,
  addLineSegment,
  addPoint,
  deleteElements,
  deleteLine,
  deleteLineSegment,
  deletePoint,
  editLine,
  editLineSegment,
  moveBezierLineSegment,
  moveElements,
  moveLine,
  movePoint,
  moveStraightLineSegment,
}
