// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2023- Mapiah Ltda
part of '../mp_command.dart';

enum MPCommandType {
  addArea,
  addAreaBorderTHID,
  addElement,
  addEmptyLine,
  addLine,
  addLineSegment,
  addPoint,
  addScrap,
  addXTherionImageInsertConfig,
  editAreaType,
  editLineSegment,
  editLineType,
  editPointType,
  moveArea,
  moveBezierLineSegment,
  moveLine,
  movePoint,
  moveStraightLineSegment,
  multipleElements,
  removeArea,
  removeAreaBorderTHID,
  removeAttrOptionFromElement,
  removeElement,
  removeEmptyLine,
  removeLine,
  removeLineSegment,
  removeOptionFromElement,
  removePoint,
  removeScrap,
  removeXTherionImageInsertConfig,
  reorderImages,
  reorderScraps,
  replaceLineSegments,
  setAttrOptionToElement,
  setOptionToElement,
}
