part of '../mp_command.dart';

enum MPCommandType {
  addArea,
  addAreaBorderTHID,
  addElement,
  addLine,
  addLineSegment,
  addPoint,
  addScrap,
  addXTherionImageInsertConfig,
  editAreaType,
  editLineSegment,
  editLineType,
  editPointType,
  moveArea,
  moveBezierLineSegment,
  moveLine,
  movePoint,
  moveStraightLineSegment,
  multipleElements,
  removeArea,
  removeAreaBorderTHID,
  removeAttrOptionFromElement,
  removeElement,
  removeLine,
  removeLineSegment,
  removeOptionFromElement,
  removePoint,
  removeScrap,
  removeXTherionImageInsertConfig,
  replaceLineSegments,
  setAttrOptionToElement,
  setOptionToElement,
}
