// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2023- Mapiah Ltda
enum MPButtonType {
  addArea,
  addElement,
  addImage,
  addLine,
  addLineToArea,
  addPoint,
  addScrap,
  addXTherionImageInsertConfig,
  changeScrap,
  chooseTHConfigAndRunTherion,
  nodeEdit,
  optionsEdit,
  redo,
  remove,
  removeXTherionImageInsertConfig,
  runTherion,
  select,
  undo,
  zoomAllFile,
  zoomAllScrap,
  zoomIn,
  zoomOneToOne,
  zoomOptions,
  zoomOut,
  zoomSelection,
  zoomSelectionWindow,
}
